package ai.qodo.dao;
import ai.qodo.DataAccessApplication;


import ai.qodo.pojo.Order;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(classes = {DataAccessApplication.class, TestConfig.class})
@TestPropertySource(locations = "classpath:application-test.properties")
class OrderDaoTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private OrderDao orderDao;

    @BeforeEach
    void setUp() {
        // Clean database before each test
        jdbcTemplate.execute("DELETE FROM orders");
    }

    @Test
    void testCreateOrder_WithValidData_Success() {
        // Arrange
        String orderNumber = "ORD-001";
        int customerId = 1001;

        // Act
        orderDao.createOrder(orderNumber, customerId);

        // Assert
        List<Order> orders = orderDao.readOrders();
        assertEquals(1, orders.size());
        Order order = orders.get(0);
        assertEquals(orderNumber, order.getOrderNumber());
        assertEquals(customerId, order.getCustomerId());
        assertNotNull(order.getOrderDate());
    }

    @Test
    void testCreateOrder_WithZeroCustomerId_Success() {
        // Arrange
        String orderNumber = "ORD-002";
        int customerId = 0;

        // Act
        orderDao.createOrder(orderNumber, customerId);

        // Assert
        List<Order> orders = orderDao.readOrders();
        assertEquals(1, orders.size());
        assertEquals(0, orders.get(0).getCustomerId());
    }

    @Test
    void testCreateOrder_WithNegativeCustomerId_Success() {
        // Arrange - Testing edge case
        String orderNumber = "ORD-003";
        int customerId = -1;

        // Act
        orderDao.createOrder(orderNumber, customerId);

        // Assert
        List<Order> orders = orderDao.readOrders();
        assertEquals(1, orders.size());
        assertEquals(-1, orders.get(0).getCustomerId());
    }

    @Test
    void testUpdateOrder_WithValidData_Success() {
        // Arrange - Create initial order
        orderDao.createOrder("ORD-100", 5000);
        List<Order> initialOrders = orderDao.readOrders();
        int orderId = initialOrders.get(0).getId();

        // Act - Update the order
        String newOrderNumber = "ORD-100-UPDATED";
        int newCustomerId = 5001;
        orderDao.updateOrder(orderId, newOrderNumber, newCustomerId);

        // Assert
        List<Order> updatedOrders = orderDao.readOrders();
        assertEquals(1, updatedOrders.size());
        Order updatedOrder = updatedOrders.get(0);
        assertEquals(newOrderNumber, updatedOrder.getOrderNumber());
        assertEquals(newCustomerId, updatedOrder.getCustomerId());
    }

    @Test
    void testUpdateOrder_NonExistentId_NoEffect() {
        // Arrange
        orderDao.createOrder("ORD-200", 2000);

        // Act - Try to update non-existent order
        orderDao.updateOrder(99999, "FAKE-ORDER", 9999);

        // Assert - Original order should remain unchanged
        List<Order> orders = orderDao.readOrders();
        assertEquals(1, orders.size());
        assertEquals("ORD-200", orders.get(0).getOrderNumber());
        assertEquals(2000, orders.get(0).getCustomerId());
    }

    @Test
    void testReadOrders_EmptyDatabase_ReturnsEmptyList() {
        // Act
        List<Order> orders = orderDao.readOrders();

        // Assert
        assertNotNull(orders);
        assertTrue(orders.isEmpty());
    }

    @Test
    void testReadOrders_MultipleRecords_ReturnsAllRecords() {
        // Arrange
        orderDao.createOrder("ORD-301", 3001);
        orderDao.createOrder("ORD-302", 3002);
        orderDao.createOrder("ORD-303", 3003);

        // Act
        List<Order> orders = orderDao.readOrders();

        // Assert
        assertEquals(3, orders.size());
    }

    @Test
    void testReadOrders_VerifyTimestamp_AutoGenerated() {
        // Arrange
        String orderNumber = "ORD-400";
        int customerId = 4000;
        orderDao.createOrder(orderNumber, customerId);

        // Act
        List<Order> orders = orderDao.readOrders();

        // Assert
        assertEquals(1, orders.size());
        Order order = orders.get(0);
        assertNotNull(order.getOrderDate(), "Order date should be auto-generated");
    }

    @Test
    void testOrderRowMapper_CorrectMapping_AllFieldsSet() {
        // Arrange
        String orderNumber = "ORD-500";
        int customerId = 5000;
        orderDao.createOrder(orderNumber, customerId);

        // Act
        List<Order> orders = orderDao.readOrders();

        // Assert
        assertEquals(1, orders.size());
        Order order = orders.get(0);
        assertNotNull(order.getId());
        assertTrue(order.getId() > 0);
        assertEquals(orderNumber, order.getOrderNumber());
        assertEquals(customerId, order.getCustomerId());
        assertNotNull(order.getOrderDate());
    }

    @Test
    void testCreateOrder_WithEmptyOrderNumber_Success() {
        // Arrange - Testing edge case
        String orderNumber = "";
        int customerId = 6000;

        // Act
        orderDao.createOrder(orderNumber, customerId);

        // Assert
        List<Order> orders = orderDao.readOrders();
        assertEquals(1, orders.size());
        assertEquals("", orders.get(0).getOrderNumber());
    }

    @Test
    void testCreateOrder_WithLongOrderNumber_Success() {
        // Arrange - Testing edge case with long order number
        String orderNumber = "ORD-" + "X".repeat(40); // 44 characters total
        int customerId = 7000;

        // Act
        orderDao.createOrder(orderNumber, customerId);

        // Assert
        List<Order> orders = orderDao.readOrders();
        assertEquals(1, orders.size());
        assertEquals(orderNumber, orders.get(0).getOrderNumber());
    }
}
